### ISSUE TITLE
Green dot with black square

### ISSUE THREAD

**Issue by Viperkeeper** [aronCiucu/DCSTheWay#181]
Been using the way for a while.  Had not used it since the most recent updates to DCS.  Now I have the green dot and a black square of the F10 map.  See image.
![Uploading Screen Shot 10-21-24 at 09.21 PM.PNG…]()

**Comment by Viperkeeper** [comment]
![Screen Shot 10-21-24 at 09 21 PM](https://github.com/user-attachments/assets/4007034c-2e2d-4bde-b95a-143bd263f285)

**Comment by Viperkeeper** [comment]
I even uninstalled DCS and that didn't correct this issue.  The waypoints generated are not so accurate.

**Comment by aronCiucu** [comment]
Hello, you seem to be using an old version of TheWay, try to remove it (and it's files in Saved Games) then follow the newest install instructions again

**Comment by Viperkeeper** [comment]
Thanks for your reply.  I really enjoy your app.  I thought I downloaded 
the latest version ( TheWayV250.Zip) this is the version I first noticed 
the issue.  I uninstalled the previous version and discovered this bug.  
I also tried repair DCS and that failed to remove the bug, so I 
uninstalled DCS and reinstalled it, still the problem persists.

Thanks for your support.

Al


------ Original Message ------
From "Aron Daniel" ***@***.***>
To "aronCiucu/DCSTheWay" ***@***.***>
Cc "Viperkeeper" ***@***.***>; "Author" 
***@***.***>
Date 10/27/2024 7:02:26 AM
Subject Re: [aronCiucu/DCSTheWay] Green dot with black square (Issue 
#181)

**Comment by aronCiucu** [comment]
Version 250 is the latest one, however the bug you've experienced was fixed in this one. Try to remove every trace of TheWay from `Saved Games/DCS/Scripts` then install again following the instructions

**Comment by Viperkeeper** [comment]
Aron,

I tried to remove every trace of the old version I could find. and 
reinstalled V250. I still have the same issue.

Al


------ Original Message ------
From "Aron Daniel" ***@***.***>
To "aronCiucu/DCSTheWay" ***@***.***>
Cc "Viperkeeper" ***@***.***>; "Author" 
***@***.***>
Date 10/28/2024 7:23:33 AM
Subject Re: [aronCiucu/DCSTheWay] Green dot with black square (Issue 
#181)
